version: 2.1

jobs:

  build:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "installing packages"
      - run: npm install
      - save_cache:
          key: "my-npm-packages"
          paths:
            - /src/node_modules
      - run: npm run lint 

  test:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "testing"
      - restore_cache:
          keys: 
            - "my-npm-packages"
      - run: npm install
      - run: npm run test
  
  analyze:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: echo "analysing"
      - run: npm audit

workflows:
  workflow_name:
    jobs:
      - build
      - test:
          requires:
            - build           
      - analyze:
          requires:
            - test